// Code generated by protoc-gen-go. DO NOT EDIT.
// source: header.proto

package scnet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	PacketType           uint32   `protobuf:"varint,1,opt,name=packetType,proto3" json:"packetType,omitempty"`
	ReqCb                int32    `protobuf:"varint,2,opt,name=req_cb,json=reqCb,proto3" json:"req_cb,omitempty"`
	ResCb                int32    `protobuf:"varint,3,opt,name=res_cb,json=resCb,proto3" json:"res_cb,omitempty"`
	AuthToken            uint32   `protobuf:"varint,4,opt,name=authToken,proto3" json:"authToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_6398613e36d6c2ce, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetPacketType() uint32 {
	if m != nil {
		return m.PacketType
	}
	return 0
}

func (m *Header) GetReqCb() int32 {
	if m != nil {
		return m.ReqCb
	}
	return 0
}

func (m *Header) GetResCb() int32 {
	if m != nil {
		return m.ResCb
	}
	return 0
}

func (m *Header) GetAuthToken() uint32 {
	if m != nil {
		return m.AuthToken
	}
	return 0
}

func init() {
	proto.RegisterType((*Header)(nil), "scnet.Header")
}

func init() { proto.RegisterFile("header.proto", fileDescriptor_6398613e36d6c2ce) }

var fileDescriptor_6398613e36d6c2ce = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0x4d, 0x4c,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x4e, 0xce, 0x4b, 0x2d, 0x51,
	0x2a, 0xe1, 0x62, 0xf3, 0x00, 0x0b, 0x0b, 0xc9, 0x71, 0x71, 0x15, 0x24, 0x26, 0x67, 0xa7, 0x96,
	0x84, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x21, 0x89, 0x08, 0x89, 0x72,
	0xb1, 0x15, 0xa5, 0x16, 0xc6, 0x27, 0x27, 0x49, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0xb1, 0x16,
	0xa5, 0x16, 0x3a, 0x27, 0x41, 0x84, 0x8b, 0x41, 0xc2, 0xcc, 0x30, 0xe1, 0x62, 0xe7, 0x24, 0x21,
	0x19, 0x2e, 0xce, 0xc4, 0xd2, 0x92, 0x8c, 0x90, 0xfc, 0xec, 0xd4, 0x3c, 0x09, 0x16, 0xb0, 0x61,
	0x08, 0x01, 0x27, 0x69, 0x2e, 0xce, 0xe4, 0xfc, 0x5c, 0x3d, 0xb0, 0x13, 0x9c, 0xb8, 0x83, 0x9d,
	0xfd, 0x52, 0x4b, 0x02, 0xc0, 0x36, 0xed, 0x62, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xd0, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x32, 0xfa, 0x83, 0x41, 0xb0, 0x00, 0x00, 0x00,
}
