// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type DummyPacket1 struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyPacket1) Reset()         { *m = DummyPacket1{} }
func (m *DummyPacket1) String() string { return proto.CompactTextString(m) }
func (*DummyPacket1) ProtoMessage()    {}
func (*DummyPacket1) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *DummyPacket1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyPacket1.Unmarshal(m, b)
}
func (m *DummyPacket1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyPacket1.Marshal(b, m, deterministic)
}
func (m *DummyPacket1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyPacket1.Merge(m, src)
}
func (m *DummyPacket1) XXX_Size() int {
	return xxx_messageInfo_DummyPacket1.Size(m)
}
func (m *DummyPacket1) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyPacket1.DiscardUnknown(m)
}

var xxx_messageInfo_DummyPacket1 proto.InternalMessageInfo

func (m *DummyPacket1) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *DummyPacket1) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type DummyPacket2 struct {
	StrArr               []string `protobuf:"bytes,3,rep,name=strArr,proto3" json:"strArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyPacket2) Reset()         { *m = DummyPacket2{} }
func (m *DummyPacket2) String() string { return proto.CompactTextString(m) }
func (*DummyPacket2) ProtoMessage()    {}
func (*DummyPacket2) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *DummyPacket2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyPacket2.Unmarshal(m, b)
}
func (m *DummyPacket2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyPacket2.Marshal(b, m, deterministic)
}
func (m *DummyPacket2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyPacket2.Merge(m, src)
}
func (m *DummyPacket2) XXX_Size() int {
	return xxx_messageInfo_DummyPacket2.Size(m)
}
func (m *DummyPacket2) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyPacket2.DiscardUnknown(m)
}

var xxx_messageInfo_DummyPacket2 proto.InternalMessageInfo

func (m *DummyPacket2) GetStrArr() []string {
	if m != nil {
		return m.StrArr
	}
	return nil
}

func init() {
	proto.RegisterType((*Ping)(nil), "example.Ping")
	proto.RegisterType((*DummyPacket1)(nil), "example.DummyPacket1")
	proto.RegisterType((*DummyPacket2)(nil), "example.DummyPacket2")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xd8, 0xb8,
	0x58, 0x02, 0x32, 0xf3, 0xd2, 0x95, 0x6c, 0xb8, 0x78, 0x5c, 0x4a, 0x73, 0x73, 0x2b, 0x03, 0x12,
	0x93, 0xb3, 0x53, 0x4b, 0x0c, 0x85, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x31, 0x2e, 0xb6, 0xbc, 0xd2, 0xdc, 0xa4, 0xd4,
	0x22, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0x49, 0x0d, 0x45, 0xb7, 0x11, 0x48,
	0x5d, 0x71, 0x49, 0x91, 0x63, 0x51, 0x91, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0x67, 0x10, 0x94, 0xe7,
	0xa4, 0xc2, 0x25, 0x98, 0x9c, 0x9f, 0xab, 0x57, 0x9c, 0x9c, 0x97, 0x5a, 0xa2, 0x07, 0x75, 0x82,
	0x13, 0x4f, 0xb0, 0xb3, 0x5f, 0x6a, 0x89, 0x2b, 0x84, 0xb7, 0x8b, 0x89, 0x21, 0x89, 0x0d, 0xec,
	0x46, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0x16, 0x0c, 0xda, 0xb4, 0x00, 0x00, 0x00,
}
